language: node_js
node_js:
  - '8'

before_install:
  - rm -rf client-app/ && git clone https://github.com/maestro-server/client-app.git client-app/
  - rm -rf server-app/ && git clone https://github.com/maestro-server/server-app.git server-app/
  - rm -rf discovery-api/ && git clone https://github.com/maestro-server/discovery-api.git discovery-api/
  - rm -rf report-app/ && git clone https://github.com/maestro-server/report-app.git report-app/
  - rm -rf scheduler-app/ && git clone https://github.com/maestro-server/scheduler-app.git scheduler-app/
  - rm -rf data-app/ && git clone https://github.com/maestro-server/data-app.git data-app/
  - rm -rf analytics-front/ && git clone https://github.com/maestro-server/analytics-front.git analytics-front/
  - rm -rf analytics-maestro/ && git clone https://github.com/maestro-server/analytics-maestro.git analytics-maestro/
  - rm -rf audit-app/ && git clone https://github.com/maestro-server/audit-app.git audit-app/


jobs:
  include:
    - stage: standalone maestro
      before_install:
        - npm run build --prefix client-app/
        - npm run build --prefix audit-app/

      install:
        - cp docker-all-in-one/Dockerfile ./Dockerfile

      script:
        - docker build -f Dockerfile -t standalone-maestro .
      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag standalone-maestro $DOCKER_USER/standalone-maestro:latest

