language: minimal
before_install:
  - git clone https://github.com/maestro-server/client-app.git client-app
  - git clone https://github.com/maestro-server/server-app.git server-app/
  - git clone https://github.com/maestro-server/discovery-api.git discovery-api/
  - git clone https://github.com/maestro-server/report-app.git report-app/
  - git clone https://github.com/maestro-server/scheduler-app.git scheduler-app/
  - git clone https://github.com/maestro-server/data-app.git data-app/
  - git clone https://github.com/maestro-server/analytics-front.git analytics-front//
  - git clone https://github.com/maestro-server/analytics-maestro.git analytics-maestro/
  - git clone https://github.com/maestro-server/audit-app.git audit-app/


jobs:
  include:
    - stage: standalone maestro
      install:
        - cp docker-all-in-one/Dockerfile ./Dockerfile
      script:
        - docker build -f Dockerfile -t standalone-maestro-base .

