---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: rabbitmq
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - name: mq-rabbitmq
          containerPort: 15672
          hostPort: 15672
        - name: port-rabbitmq
          containerPort: 5672
          hostPort: 5672