apiVersion: v1
kind: Service
metadata:
  name: external-analytics-front
spec:
  ports:
  - port: 31299
    nodePort: 31299
    targetPort: afront-port
  selector:
    app: maestro-analytics-front
  type: NodePort
