apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-client
spec:
  replicas: 2
  template: 
    metadata: 
      labels:
        app: maestro-client
    spec:
      containers:
      - name: maestro-client
        image: maestroserver/client-maestro
        ports: 
        - name: mclient-port
          containerPort: 80
        env:
        - name: API_URL
          value: "http://localhost:31241"
        - name: STATIC_URL
          value: "http://localhost:31241/static/"
        - name: ANALYTICS_URL
          value: "http://localhost:31299"
        - name: WEBSOCKET_URL
          value: "ws://localhost:31800"
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
          limits:
            cpu: 300m
            memory: 0.3Gi
