apiVersion: v1
kind: Service
metadata:
  name: external-websocket
spec:
  selector:
    app: maestro-websocket
  type: LoadBalancer
  ports:
  - port: 8443
    name: ext-ws
    targetPort: mwebsocket-port
  - port: 80
    name: acme-ws
    targetPort: acme-port