---
version: '3'

services:
    maestro:
        image: maestroserver/standalone
        ports:
        - 80:80
        - 8888:8888
        - 8000:8000
        - 9999:9999
        environment:
        - "MAESTRO_MONGO_URI=mongodb://mongodb:27017"
        - "CELERY_BROKER_URL=amqp://rabbitmq:5672"
        volumes:
        - "vlm:/data/artifacts"
        depends_on:
        - mongodb
        - rabbitmq
    
    rabbitmq:
        image: rabbitmq:3-management
        ports:
        - "15672:15672"
        - "5672:5672"
        
    mongodb:
        image: mongo
        volumes:
        - mongodb2:/data/db
        ports:
        - "27018:27017"

volumes:
    vlm: {}
    mongodb2: {}
