apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-analytics
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-analytics
    spec:
      containers:
      - name: maestro-analytics
        image: maestroserver/analytics-maestro
        ports: 
        - name: analytics-port
          containerPort: 5020
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://internal-rabbit:5672"
          - name: MAESTRO_DATA_URI
            value: "http://internal-data:5010"
