apiVersion: v1
kind: Service
metadata:
  name: external-analytics-front
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  selector:
    app: maestro-analytics-front
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: afront-port