---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-analytics-worker
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-analytics-worker
    spec:
      containers:
      - name: maestro-analytics-worker
        image: maestroserver/analytics-maestro-celery
      
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "celery -A app.celery status | grep -o ': OK'"
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 15

        resources:
          requests:
            cpu: "10m"

        env:
          - name: CELERY_BROKER_URL
            value: "amqp://internal-rabbit:5672"
          - name: MAESTRO_DATA_URI
            value: "http://internal-data:5010"
          - name: MAESTRO_ANALYTICS_FRONT_URI
            value: "http://internal-analytics-front:9999"
          - name: MAESTRO_WEBSOCKET_URI
            value: "https://websocket.maestroserver.io:8443"