apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-data
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-data
    spec:
      containers:
      - name: maestro-data
        image: maestroserver/data-maestro
        ports: 
        - name: mdata-port
          containerPort: 5010
        env:
          - name: MAESTRO_MONGO_URI
            value: "mongodb://mongo:27017"
          - name: MAESTRO_MONGO_DATABASE
            value: "maestro-client"
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
          limits:
            cpu: 300m
            memory: 0.5Gi