---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maildev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - name: maildev
        image: djfarrelly/maildev
        ports:
        - name: smtp
          containerPort: 25
        - name: mail-http
          containerPort: 80