apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-discovery
  name: external-discovery
spec:
  ports:
    - port: 5000
      targetPort: mdiscovery-port
      protocol: TCP
  selector:
    name: maestro-discovery