apiVersion: v1
kind: Service
metadata:
  labels:
    name: maestro-discovery-svc
  name: maestro-discovery-svc
spec:
  ports:
    - port: 5000
      targetPort: mdiscovery-port
      protocol: TCP
  selector:
    name: maestro-discovery