---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-discovery-worker
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-discovery-worker
    spec:
      containers:
      - name: maestro-discovery-worker
        image: maestroserver/discovery-maestro-celery
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://internal-rabbit-svc:5672"
          - name: MAESTRO_DATA_URI
            value: "http://maestro-data-svc:5010"
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
          limits:
            cpu: 300m
            memory: 0.5Gi