apiVersion: v1
kind: Service
metadata:
  name: maestro-websocket-svc
spec:
  ports:
  - port: 31800
    nodePort: 31800
    targetPort: mwebsocket-port
  selector:
    app: maestro-websocket
  type: NodePort
