apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-analytics-front
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-analytics-front
    spec:
      containers:
      - name: maestro-analytics-front
        image: maestroserver/analytics-front-maestro
        ports: 
        - name: afront-port
          containerPort: 9999
        env:
          - name: MAESTRO_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongouri
                key: MAESTRO_MONGO_URI
          - name: MAESTRO_MONGO_DATABASE
            value: "maestro-client"
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
          limits:
            cpu: 300m
            memory: 0.5Gi
