---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-reports-worker
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-reports-worker
    spec:
      containers:
      - name: maestro-reports-worker
        image: maestroserver/reports-maestro-celery

        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "celery -A app.celery status | grep -o ': OK'"
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 15

        resources:
          requests:
            cpu: "10m"

        env:
          - name: CELERY_BROKER_URL
            value: "amqp://internal-rabbit:5672"
          - name: MAESTRO_DATA_URI
            value: "http://internal-data:5010"
          - name: MAESTRO_WEBSOCKET_URI
            value: "https://websocket.maestroserver.io:8443"
          - name: MAESTRO_REPORT_URI
            value: "http://internal-reports:5005"
          - name: MAESTRO_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongosrv
                key: MAESTRO_MONGO_URI
          - name: MAESTRO_MONGO_DATABASE
            value: "maestro-reports"
