---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-discovery-worker
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-discovery-worker
    spec:
      containers:
      - name: maestro-discovery-worker
        image: maestroserver/discovery-maestro-celery
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://internal-rabbit:5672"
          - name: MAESTRO_DATA_URI
            value: "http://internal-data:5010"
          - name: MAESTRO_AUDIT_URI
            value: "http://internal-audit:10900"
          - name: MAESTRO_WEBSOCKET_URI
            value: "http://internal-websocket:8000"
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
          limits:
            cpu: 600m
            memory: 1Gi
