apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: maestro-client
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: maestro-client:q!

    spec:
      containers:
      - name: maestro-client
        image: 811322200214.dkr.ecr.us-east-1.amazonaws.com/ecp-offerservice:1.0
        ports: 
        - containerPort: 8000
        env:  
        - name: http_proxy
          value: $(NODE_NAME):4141
